### ISSUE TITLE
Centos 7 (Salt) Bootstrap problem

### ISSUE THREAD

**Issue by vampywiz17** [uyuni-project/uyuni#2156]
Hello there,

i bootsraped a centos7 client. set everything (gpg, etc..) but if i try to update i get this:

`[root@hun25-12v ~]# yum update
Loaded plugins: fastestmirror, susemanagerplugin, yumnotify
Repository 'susemanager:centos7-uyuni-client-x86_64': Error parsing config: Error parsing "repo_gpgcheck = 'default'": invalid boolean value
Repository 'susemanager:centos7-x86_64-updates': Error parsing config: Error parsing "repo_gpgcheck = 'default'": invalid boolean value
Repository 'susemanager:centos7-x86_64': Error parsing config: Error parsing "repo_gpgcheck = 'default'": invalid boolean value
Loading mirror speeds from cached hostfile
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 To enable Red Hat Subscription Management repositories:
     subscription-manager repos --enable <repo>
 To enable custom repositories:
     yum-config-manager --enable <repo>
[root@hun25-12v ~]#
`

in `/etc/yum.repos.d/susemanager\:channels.repo` i found this:

```
repo_gpgcheck=default
pkg_gpgcheck=default

```

If i know correctly, this values is only accept "on" or "off" variables, so the "default" is not recognizable.

If i comment it , the update is working well. But unfortunately the salt is write it back.

Any idea, how to fix it permanently?

**Comment by paususe** [comment]
@admd could you please take a look?

**Comment by vampywiz17** [comment]
Salt get same error on centos client:

```
2020-04-27 10:53:35,792 [salt.utils.templates:180 ][ERROR   ][6382] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 402, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'repo_gpgcheck'
2020-04-27 10:53:35,797 [salt.state       :323 ][ERROR   ][6382] Unable to manage file: Jinja variable 'dict object' has no attribute 'repo_gpgcheck'

```

**Comment by admd** [comment]
Hi @vampywiz17 
> Any idea, how to fix it permanently?

If you will set `sign_metadata` property to 0 in `rhn.conf` file then `gpgcheck` and `repo_gpgcheck` will be set to 0 while `pkg_gpgcheck` will depend on `Enable GPG Check` checkbox for a particular channl.

```
 # If set to 1 all generated repository metadata will be signed
sign_metadata = 0
```

**Comment by vampywiz17** [comment]
I edit this line in server `var/rhn/rhn.conf,` but i get the same error.

**Comment by admd** [comment]
@vampywiz17 
Forgot to mention that Pillars needs to be regenerated and for that, in this case, please unassign/assign the channels.

If problem defined in https://github.com/uyuni-project/uyuni/issues/2156#issue-606215402
still persist then if possible do share pillars for that particular minions. 

You can get the channels pillar using the following command

`salt <minion.id>  pillar.item channels`

**Comment by vampywiz17** [comment]
@admd 

Ok now it is working, thx!

The GPG sign will be fixed? Please report it in to this! Thanks a lot!

**Comment by vampywiz17** [comment]
@admd 

Unfortunately it not help ... It solve the problem on Centos client, but ubuntu client get this:

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://hun25-14v.hft.rosenberger.local:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B61072*****************
`

**Comment by mateiw** [comment]
@vampywiz17 try the following:
- `mgr-sign-metadata-ctl disable` on the server. 
- regenerate the channels metadata: `mgr-sign-metadata-ctl regen-metadata`.
- reasign the channels to the Ubuntu client

**Comment by vampywiz17** [comment]
@mateiw 

I will try it.

Any progress to this perma. fix?

**Comment by vampywiz17** [comment]
@mateiw It working, Thanks! But of course it generate a lot of warnings.... I hope it will fixed soon...

**Comment by zwei42** [comment]
The problem seems to be in java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java

Starting at line 135 you can see that "default"  is hardcoded in pillar data generation.

      if (ConfigDefaults.get().isMetadataSigningEnabled()) {
            chanProps.put("gpgcheck", chan.isGPGCheck() ? "1" : "0");
            // three state field. yes, no or default
            chanProps.put("repo_gpgcheck", "default");
            chanProps.put("pkg_gpgcheck", "default");


Btw in RHEL7/CentOS7   pkg_gpgcheck is not implemented,    repo_gpgcheck must be either 0 or 1 ("yes" and "no" are not valid states either)

**Comment by vampywiz17** [comment]
@zwei42 where is this file on the installed system?

**Comment by zwei42** [comment]
Nowhere.
This is in the source code.

vampywiz17 <notifications@github.com> ezt írta (időpont: 2020. máj. 15., P,
9:34):

**Comment by vampywiz17** [comment]
@zwei42 Yes, sorry i recognise it after i wrote the comment.

**Comment by zwei42** [comment]
In case of Ubuntu clients, disabling the metadata signing leaves the gpg signatures (Release.gpg).
After updating channel data and generating new Release file,  the signature will be invalid, and will generate plenty of errors on the client.

Release files are located in /var/cache/rhn/repodata/<channelname>/

**Comment by vampywiz17** [comment]
> In case of Ubuntu clients, disabling the metadata signing leaves the gpg signatures (Release.gpg).
> After updating channel data and generating new Release file, the signature will be invalid, and will generate plenty of errors on the client.
> 
> Release files are located in /var/cache/rhn/repodata/channelname/
> 
> They can be signed manually with something like:
> `gpg --default-key ` your-gpg-key `-abs -o Release.gpg Release`
> 
> GPG key used for signing metadata can be found: `gpg --list-keys`
> (Passphrase of key that was used by Uyuni can be found in /etc/rhn/signing.conf)
> 
> You might have to import public key on the client with `apt-key `

Yeah, now i wait the fix, because i use more Ubuntu with centos . I Hope it fix it soon.

**Comment by zwei42** [comment]
The salt template can also be changed.
I left gpg signing enabled, and  set repo_gpgcheck=0  in 
/usr/share/susemanager/salt/channels/channels.repo

This way neither Ubuntu and RedHat clients complain.

**Comment by vampywiz17** [comment]
@zwei42 

Good idea, i edit this file. But it start this lines:

```
# Channels managed by SUSE Manager
# Do not edit this file, changes will be overwritten
```

it is no problem?

**Comment by juliogonzalez** [comment]
> it is no problem?

Could work... temporary. As it says, it will be overwritten with a new Uyuni version (that maybe will go out this week).

I wonder if this some kind of regression. I didn't see this bug when I tested CentOS7 months ago (never did any changes to `rhn.conf` nor used `mgr-sign-metadata-ctl`, and I am pretty sure I installed a package as part of the smoke tests.

@admd @mateiw thoughts?

**Comment by zwei42** [comment]
metadata signing  of repo data is not enabled by default   You have to enable it manually with `mgr-sign-metadata-ctl` (...and deb based clients, like Ubuntu, keep complaining without it.)
When enabled , then  _MinionGeneralPillarGenerator.java_   generates the wrong pillar data.
It should be fixed, but until then, this workaround with the salt template can help.

Btw. I think it is not really required that the java engine generate the exact config flags and values. It could store arbitary variables in pillar data,  and salt can render the exact config. This way it is easier to adapt to changing OS config file syntaxt. (No need to recompile, easyer to handle different OS flavours, etc.)

**Comment by mcalmer** [comment]
I had to have a deeper look into it as we got an official support request and it turned out that yum and zypp behave very different. So I had to split out the configuration and hope it is now fixed.

**Comment by zwei42** [comment]
I got the patch yesterday, applied it, and looks good. :) :)

**Comment by zwei42** [comment]
ehh, one issue still remains.
It seems that yum does not use imported gpg keys when checking channel metadata signature.
There is a seaparate trustdb for each channel.
Because of this a gpg key has to be specified for each channels  with "gpgkey=<key url>"

In file /usr/share/susemanager/salt/channels/channels.repo  the following option should be added to the RedHat block:

`gpgkey=https://{{ args['host'] }}/pub/mgr-gpg-pub.key`

(The key URL is the same as in the documentation)
