### ISSUE TITLE
 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>

### ISSUE THREAD

**Issue by EthanB11** [uyuni-project/uyuni#2902]
# Additional Information

Having issues syncing 2 Fedora 32 packages for a few Uyuni releases. Packages seems to download, but not import. I found one other closed issue like this https://github.com/uyuni-project/uyuni/issues/2647, but my log file isn't showing a download error and I have already bypassed IPS for my Uyuni host. It's interesting the other ticket also shows package kicad-packages3d-5.1.5

## Version of Uyuni Server and Proxy (if used)
````
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2020.09-98.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2020.09-98.2.uyuni.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
````

## Details about issue
````2020/11/24 11:43:03 -05:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'fedora32-x86_64', '--type', 'yum', '--non-interactive']
2020/11/24 11:43:03 -05:00 Sync of channel started.
2020/11/24 11:43:12 -05:00 Repo URL: https://mirrors.fedoraproject.org/metalink?repo=fedora-32&arch=x86_64
2020/11/24 11:43:12 -05:00     Packages in repo:             55327
2020/11/24 11:46:23 -05:00     Packages already synced:      55325
2020/11/24 11:46:23 -05:00     Packages to sync:                 2
2020/11/24 11:46:23 -05:00     New packages to download:         2
2020/11/24 11:46:23 -05:00   Downloading packages:
2020/11/24 11:46:29 -05:00     1/2 : kicad-packages3d-5.1.5-2.fc32.noarch.rpm
2020/11/24 11:46:29 -05:00     2/2 : python3-graph-tool-2.29-2.fc32.x86_64.rpm
2020/11/24 11:46:30 -05:00 Importing packages started.
2020/11/24 11:46:30 -05:00
2020/11/24 11:46:30 -05:00   Importing packages to DB:
2020/11/24 11:46:32 -05:00 list index out of range
2020/11/24 11:46:32 -05:00   Package batch #1 of 1 completed...
2020/11/24 11:46:32 -05:00 Importing packages finished.
2020/11/24 11:46:32 -05:00
2020/11/24 11:46:32 -05:00   Linking packages to the channel.
2020/11/24 11:46:32 -05:00 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
2020/11/24 11:46:32 -05:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 592, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1107, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 126, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 822, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 814, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2493, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'kicad-packages3d', 'epoch': 1, 'version': '5.1.5', 'release': '2.fc32', 'arch': 'noarch', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {342: 'fedora32-x86_64'}, 'checksum_list': None, 'checksum': 'a4a4f02a0a56860de069ff29de789e497ed62587cc8190a7c3bc8bca2f53ccfa', 'checksum_type': 'sha256', 'checksums': {'sha256': 'a4a4f02a0a56860de069ff29de789e497ed62587cc8190a7c3bc8bca2f53ccfa'}, 'name_id': 149039, 'evr_id': 172962, 'package_arch_id': 100, 'nevra_id': 683146, 'checksum_id': 27626610}] in table rhnPackage
````

**Comment by StefanSa** [comment]
Seems to be the same bug #3040

**Comment by mcalmer** [comment]
@EthanB11 can you see errors in the postgresql logs of that day and time?

**Comment by EthanB11** [comment]
I do not see errors in the postgresql data log for that date and time. I am looking at /var/lib/pgsql/data/log/postresql-2020-11-24_000000.log that seems to be the only place I can find postgresql logs. Anywhere else to look?

**Comment by EthanB11** [comment]
I am also getting errors syncing Ubuntu repos after the upgrade to 2020.11 from the previous release. I can open a new issue for this if it's not related.

````
Syncing Channel 'ubuntu-2004-amd64-main-updates-uyuni' failed:

Exception reported from lm3
Time: Thu Dec 17 13:50:21 2020
Exception type <class 'TypeError'>

Exception Handler Information
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 85, in __call__
    ret = self.cursor.execute(query, args)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "rhn_cnp_cid_nid_uq"
DETAIL:  Key (channel_id, name_id, package_arch_id)=(236, 20364, 134) already exists.
CONTEXT:  SQL statement "insert into rhnChannelNewestPackage
                (channel_id, name_id, evr_id, package_id, package_arch_id)
                (select channel_id,
                        name_id, evr_id,
                        package_id, package_arch_id
                   from rhnChannelNewestPackageView
                  where channel_id = channel_id_in
                    and (package_name_id_in is null
                         or name_id = package_name_id_in)
                )"
PL/pgSQL function rhn_channel.refresh_newest_package(numeric,character varying,numeric) line 9 at SQL statement


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2072, in update_newest_package_cache
    refresh_newest_package(channel_id, caller, None)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 116, in __call__
    result = Function.__call__(self, *args)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/rhnSQL/driver_postgresql.py", line 92, in __call__
    raise sql_base.SQLSchemaError(error_code, e.pgerror, e)
spacewalk.server.rhnSQL.sql_base.SQLSchemaError: (99999, 'ERROR:  duplicate key value violates unique constraint "rhn_cnp_cid_nid_uq"', 'DETAIL:  Key (channel_id, name_id, package_arch_id)=(236, 20364, 134) already exists.\nCONTEXT:  SQL statement "insert into rhnChannelNewestPackage\n                (channel_id, name_id, evr_id, package_id, package_arch_id)\n                (select channel_id,\n                        name_id, evr_id,\n                        package_id, package_arch_id\n                   from rhnChannelNewestPackageView\n                  where channel_id = channel_id_in\n                    and (package_name_id_in is null\n                         or name_id = package_name_id_in)\n                )"\nPL/pgSQL function rhn_channel.refresh_newest_package(numeric,character varying,numeric) line 9 at SQL statement\n', UniqueViolation('duplicate key value violates unique constraint "rhn_cnp_cid_nid_uq"\nDETAIL:  Key (channel_id, name_id, package_arch_id)=(236, 20364, 
 134) already exists.\nCONTEXT:  SQL statement "insert into rhnChannelNewestPackage\n                (channel_id, name_id, evr_id, package_id, package_arch_id)\n                (select channel_id,\n                        name_id, evr_id,\n                        package_id, package_arch_id\n                   from rhnChannelNewestPackageView\n                  where channel_id = channel_id_in\n                    and (package_name_id_in is null\n                         or name_id = package_name_id_in)\n                )"\nPL/pgSQL function rhn_channel.refresh_newest_package(numeric,character varying,numeric) line 9 at SQL statement\n',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 592, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1107, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 142, in submit
    affected_channels=self.affected_channel_packages, name_ids=name_ids)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2075, in update_newest_package_cache
    raise_with_tb(rhnFault(23, str(e[1]), explain=0), sys.exc_info()[2])
TypeError: 'SQLSchemaError' object does not support indexing
````

**Comment by mcalmer** [comment]
All this should be fixed with 2021.01 . 
The change is huge and cannot be applied easily.
If you need a quick solution you need to break the version compare algorithm and rollback the last change.

**Comment by EthanB11** [comment]
Just upgraded and still getting the same error

```
Syncing Channel 'fedora32-x86_64' failed:

Exception reported from lm3
Time: Fri Feb  5 12:04:52 2021
Exception type <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>

Exception Handler Information
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1127, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2505, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'kicad-packages3d', 'epoch': 1, 'version': '5.1.5', 'release': '2.fc32', 'arch': 'noarch', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {342: 'fedora32-x86_64'}, 'checksum_list': None, 'checksum': 'a4a4f02a0a56860de069ff29de789e497ed62587cc8190a7c3bc8bca2f53ccfa', 'checksum_type': 'sha256', 'checksums': {'sha256': 'a4a4f02a0a56860de069ff29de789e497ed62587cc8190a7c3bc8bca2f53ccfa'}, 'name_id': 149039, 'evr_id': 172962, 'package_arch_id': 100, 'nevra_id': 683146, 'checksum_id': 27626610}] in table rhnPackage
```

**Comment by EthanB11** [comment]
I can report the Ubuntu repos are now syncing, but Fedora 32 main is still not.

**Comment by paususe** [comment]
> I can report the Ubuntu repos are now syncing, but Fedora 32 main is still not.

What's the problem with Fedora 32? Could you please paste some error log?

**Comment by EthanB11** [comment]
They are already listed in thus bug,  no change with the fix for Ubuntu.

Ethan

**Comment by EthanB11** [comment]
Here is some detail for another on Fedora 33.

```
2021/03/28 10:58:00 -05:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'fedora33-x86_64', '--type', 'yum', '--non-interactive', '--latest', '--sync-kickstart']
2021/03/28 10:58:00 -05:00 Sync of channel started.
2021/03/28 10:58:09 -05:00 Repo URL: https://mirrors.fedoraproject.org/metalink?repo=fedora-33&arch=x86_64
2021/03/28 10:58:09 -05:00     Packages in repo:             55750
2021/03/28 11:00:43 -05:00     Packages already synced:      55748
2021/03/28 11:00:43 -05:00     Packages to sync:                 2
2021/03/28 11:00:43 -05:00     New packages to download:         2
2021/03/28 11:00:43 -05:00   Downloading packages:
2021/03/28 11:00:45 -05:00     1/2 : kernel-core-5.8.15-301.fc33.x86_64.rpm
2021/03/28 11:00:46 -05:00     2/2 : kernel-debug-core-5.8.15-301.fc33.x86_64.rpm
2021/03/28 11:00:47 -05:00 Importing packages started.
2021/03/28 11:00:47 -05:00 
2021/03/28 11:00:47 -05:00   Importing packages to DB:
2021/03/28 11:00:55 -05:00 value too long for type character varying(4000)

2021/03/28 11:00:55 -05:00   Package batch #1 of 1 completed...
2021/03/28 11:00:55 -05:00 Importing packages finished.
2021/03/28 11:00:55 -05:00 
2021/03/28 11:00:55 -05:00   Linking packages to the channel.
2021/03/28 11:00:55 -05:00 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
2021/03/28 11:00:55 -05:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1127, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2505, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'kernel-core', 'epoch': None, 'version': '5.8.15', 'release': '301.fc33', 'arch': 'x86_64', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {371: 'fedora33-x86_64'}, 'checksum_list': None, 'checksum': 'd8f263272b87175ece88f200f6b843c89c4294ee2abf630ff38485abac90fb47', 'checksum_type': 'sha256', 'checksums': {'sha256': 'd8f263272b87175ece88f200f6b843c89c4294ee2abf630ff38485abac90fb47'}, 'name_id': 99997, 'evr_id': 356021, 'package_arch_id': 120, 'nevra_id': 852402, 'checksum_id': 33486992}] in table rhnPackage
```

Also Fedora 33 update

```
2021/03/28 10:30:00 -05:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'fedora33-x86_64-updates', '--type', 'yum', '--non-interactive']
2021/03/28 10:30:00 -05:00 Sync of channel started.
2021/03/28 10:30:07 -05:00 Repo URL: https://mirrors.fedoraproject.org/metalink?repo=updates-released-f33&arch=x86_64
2021/03/28 10:30:07 -05:00     Packages in repo:             20318
2021/03/28 10:31:10 -05:00     Packages already synced:      19946
2021/03/28 10:31:10 -05:00     Packages to sync:               372
2021/03/28 10:31:10 -05:00     New packages to download:       212
2021/03/28 10:31:10 -05:00   Downloading packages:
2021/03/28 10:31:10 -05:00     1/212 : aspnetcore-runtime-3.1-3.1.13-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     2/212 : ceph-mgr-rook-15.2.10-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     3/212 : bats-1.3.0-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     4/212 : ceph-grafana-dashboards-15.2.10-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     5/212 : awf-gtk2-2.2.0-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     6/212 : cephfs-shell-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     7/212 : compat-golang-github-haproxytech-config-parser-3-devel-3.1.0-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     8/212 : clamav-unofficial-sigs-7.2.4-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     9/212 : cups-devel-2.3.3op2-3.fc33.i686.rpm
2021/03/28 10:31:10 -05:00     10/212 : cups-client-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     11/212 : cups-devel-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     12/212 : cups-filesystem-2.3.3op2-3.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     13/212 : cups-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     14/212 : cups-libs-2.3.3op2-3.fc33.i686.rpm
2021/03/28 10:31:10 -05:00     15/212 : ceph-mds-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     16/212 : cups-lpd-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     17/212 : cups-printerapp-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     18/212 : dbus-broker-28-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     19/212 : cups-libs-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     20/212 : dialect-1.2.0-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     21/212 : cups-ipptool-2.3.3op2-3.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     22/212 : freight-0.3.13-1.fc33.noarch.rpm
2021/03/28 10:31:10 -05:00     23/212 : gap-core-4.11.1-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     24/212 : gap-4.11.1-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     25/212 : dotnet-targeting-pack-3.1-3.1.13-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     26/212 : ceph-osd-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     27/212 : gdb-gdbserver-10.1-4.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     28/212 : gdk-pixbuf2-devel-2.42.4-1.fc33.i686.rpm
2021/03/28 10:31:10 -05:00     29/212 : gdk-pixbuf2-2.42.4-1.fc33.i686.rpm
2021/03/28 10:31:10 -05:00     30/212 : gdk-pixbuf2-2.42.4-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     31/212 : gdk-pixbuf2-devel-2.42.4-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     32/212 : gdk-pixbuf2-modules-2.42.4-1.fc33.i686.rpm
2021/03/28 10:31:10 -05:00     33/212 : gdk-pixbuf2-modules-2.42.4-1.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     34/212 : gjs-1.66.2-4.fc33.i686.rpm
2021/03/28 10:31:10 -05:00     35/212 : gjs-1.66.2-4.fc33.x86_64.rpm
2021/03/28 10:31:10 -05:00     36/212 : gdb-minimal-10.1-4.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     37/212 : gjs-devel-1.66.2-4.fc33.i686.rpm
2021/03/28 10:31:11 -05:00     38/212 : gjs-devel-1.66.2-4.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     39/212 : gjs-tests-1.66.2-4.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     40/212 : gnome-desktop3-3.38.5-1.fc33.i686.rpm
2021/03/28 10:31:11 -05:00     41/212 : gnome-desktop3-3.38.5-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     42/212 : gnome-desktop3-devel-3.38.5-1.fc33.i686.rpm
2021/03/28 10:31:11 -05:00     43/212 : gnome-desktop3-devel-3.38.5-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     44/212 : gnome-desktop3-tests-3.38.5-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     45/212 : golang-github-haproxytech-config-parser-devel-3.1.0-1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     46/212 : guayadeque-langpack-bg-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     47/212 : guayadeque-langpack-ca_ES-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     48/212 : guayadeque-langpack-cs-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     49/212 : guayadeque-langpack-da-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     50/212 : gdk-pixbuf2-tests-2.42.4-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     51/212 : guayadeque-langpack-de-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     52/212 : guayadeque-langpack-el-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     53/212 : guayadeque-langpack-es-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     54/212 : guayadeque-0.4.7-0.27.20210315git37840c1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     55/212 : guayadeque-langpack-fr-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     56/212 : guayadeque-langpack-hr-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     57/212 : guayadeque-langpack-hu-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     58/212 : guayadeque-langpack-is-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     59/212 : guayadeque-langpack-it-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     60/212 : guayadeque-langpack-ja-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     61/212 : guayadeque-langpack-lt-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     62/212 : guayadeque-langpack-ms-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     63/212 : guayadeque-langpack-nb-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     64/212 : guayadeque-langpack-nl-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     65/212 : guayadeque-langpack-pl-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     66/212 : guayadeque-langpack-pt-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     67/212 : guayadeque-langpack-pt_BR-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     68/212 : guayadeque-langpack-ru-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     69/212 : guayadeque-langpack-sk-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     70/212 : guayadeque-langpack-sr-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     71/212 : guayadeque-langpack-sv-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     72/212 : guayadeque-langpack-th-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     73/212 : guayadeque-langpack-tr-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     74/212 : guayadeque-langpack-uk-0.4.7-0.27.20210315git37840c1.fc33.noarch.rpm
2021/03/28 10:31:11 -05:00     75/212 : kernel-modules-internal-5.11.10-200.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     76/212 : libgusb-0.3.6-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     77/212 : latte-integrale-1.7.6-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     78/212 : libgusb-devel-0.3.6-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     79/212 : libquotient-devel-0.6.6-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     80/212 : librados2-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     81/212 : librgw2-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:11 -05:00     82/212 : libvala-0.48.15-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     83/212 : dotnet-sdk-3.1-3.1.113-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     84/212 : mesa-filesystem-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     85/212 : mesa-filesystem-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     86/212 : mesa-libEGL-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     87/212 : mesa-libEGL-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     88/212 : mesa-libEGL-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     89/212 : mesa-libEGL-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     90/212 : mesa-libGL-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     91/212 : mesa-libGL-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     92/212 : mesa-libGL-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     93/212 : mesa-libGL-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     94/212 : kernel-core-5.11.10-200.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     95/212 : mesa-libOSMesa-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     96/212 : mesa-libOSMesa-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     97/212 : mesa-libOSMesa-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     98/212 : mesa-dri-drivers-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     99/212 : kernel-debug-core-5.11.10-200.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     100/212 : mesa-libOSMesa-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     101/212 : mesa-libOpenCL-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     102/212 : mesa-libOpenCL-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     103/212 : mesa-libOpenCL-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     104/212 : mesa-libOpenCL-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     105/212 : mesa-libd3d-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     106/212 : mesa-libd3d-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     107/212 : mesa-dri-drivers-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     108/212 : mesa-libgbm-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     109/212 : mesa-libgbm-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     110/212 : mesa-libgbm-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     111/212 : mesa-libgbm-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     112/212 : mesa-libglapi-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     113/212 : mesa-libglapi-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     114/212 : mesa-libxatracker-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:12 -05:00     115/212 : mesa-libxatracker-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     116/212 : mesa-libxatracker-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:12 -05:00     117/212 : mesa-libd3d-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     118/212 : mesa-omx-drivers-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     119/212 : mesa-vulkan-devel-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     120/212 : mesa-libd3d-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     121/212 : mesa-vulkan-devel-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     122/212 : mesa-vdpau-drivers-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     123/212 : mesa-vdpau-drivers-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     124/212 : mesa-vulkan-drivers-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     125/212 : mesa-libxatracker-20.3.5-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     126/212 : mesa-vulkan-drivers-20.3.5-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     127/212 : nss-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     128/212 : nss-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     129/212 : nss-devel-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     130/212 : mozjs78-78.9.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     131/212 : nss-devel-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     132/212 : nss-pkcs11-devel-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     133/212 : nss-pkcs11-devel-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     134/212 : nss-softokn-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     135/212 : nss-softokn-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     136/212 : nss-softokn-devel-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     137/212 : nss-softokn-devel-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     138/212 : mozjs78-78.9.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     139/212 : nss-softokn-freebl-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     140/212 : nss-softokn-freebl-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     141/212 : nss-softokn-freebl-devel-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     142/212 : nss-softokn-freebl-devel-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     143/212 : nss-sysinit-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     144/212 : nss-util-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     145/212 : nss-util-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     146/212 : nss-tools-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     147/212 : nss-util-devel-3.63.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     148/212 : nss-util-devel-3.63.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     149/212 : php-laminas-authentication-2.8.0-1.fc33.noarch.rpm
2021/03/28 10:31:13 -05:00     150/212 : php-laminas-mail-2.14.0-1.fc33.noarch.rpm
2021/03/28 10:31:13 -05:00     151/212 : pipewire-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     152/212 : pipewire-0.3.24-4.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     153/212 : mozjs78-devel-78.9.0-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     154/212 : pipewire-alsa-0.3.24-4.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     155/212 : pipewire-alsa-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     156/212 : pipewire-devel-0.3.24-4.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     157/212 : pipewire-devel-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     158/212 : pipewire-gstreamer-0.3.24-4.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     159/212 : pipewire-gstreamer-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     160/212 : pipewire-jack-audio-connection-kit-0.3.24-4.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     161/212 : pipewire-jack-audio-connection-kit-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     162/212 : pipewire-plugin-jack-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     163/212 : pipewire-libs-0.3.24-4.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     164/212 : pipewire-libs-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     165/212 : pipewire-pulseaudio-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     166/212 : mozjs78-devel-78.9.0-1.fc33.i686.rpm
2021/03/28 10:31:13 -05:00     167/212 : pipewire-utils-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     168/212 : python3-allpairspy-2.5.0-1.fc33.noarch.rpm
2021/03/28 10:31:13 -05:00     169/212 : poke-libs-1.0-4.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     170/212 : python3-ceph-argparse-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     171/212 : python3-pyatspi-2.38.1-1.fc33.noarch.rpm
2021/03/28 10:31:13 -05:00     172/212 : python3-rbd-15.2.10-1.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     173/212 : python3-langdetect-1.0.8-1.fc33.noarch.rpm
2021/03/28 10:31:13 -05:00     174/212 : qt-common-4.8.7-60.fc33.noarch.rpm
2021/03/28 10:31:13 -05:00     175/212 : qt-assistant-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:13 -05:00     176/212 : qt-config-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     177/212 : qt-designer-plugin-webkit-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     178/212 : qt-designer-plugin-webkit-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     179/212 : qt-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     180/212 : qt-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     181/212 : qt-demos-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     182/212 : qt-devel-private-4.8.7-60.fc33.noarch.rpm
2021/03/28 10:31:14 -05:00     183/212 : qt-devel-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     184/212 : qt-devel-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     185/212 : qt-ibase-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     186/212 : qt-ibase-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     187/212 : qt-mysql-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     188/212 : qt-mysql-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     189/212 : qt-examples-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     190/212 : qt-odbc-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     191/212 : qt-odbc-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     192/212 : qt-postgresql-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     193/212 : qt-postgresql-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     194/212 : qt-qdbusviewer-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     195/212 : qt-tds-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     196/212 : qt-tds-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     197/212 : qt-qvfb-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     198/212 : qt-examples-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     199/212 : pipewire-doc-0.3.24-4.fc33.x86_64.rpm
2021/03/28 10:31:14 -05:00     200/212 : rubberband-devel-1.9.1-1.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     201/212 : rubberband-1.9.1-1.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     202/212 : systemd-devel-246.13-1.fc33.i686.rpm
2021/03/28 10:31:14 -05:00     203/212 : systemd-container-246.13-1.fc33.i686.rpm
2021/03/28 10:31:15 -05:00     204/212 : systemd-standalone-sysusers-246.13-1.fc33.x86_64.rpm
2021/03/28 10:31:15 -05:00     205/212 : valadoc-devel-0.48.15-1.fc33.x86_64.rpm
2021/03/28 10:31:15 -05:00     206/212 : xen-4.14.1-7.fc33.x86_64.rpm
2021/03/28 10:31:15 -05:00     207/212 : xen-ocaml-4.14.1-7.fc33.x86_64.rpm
2021/03/28 10:31:15 -05:00     208/212 : xen-ocaml-devel-4.14.1-7.fc33.x86_64.rpm
2021/03/28 10:31:15 -05:00     209/212 : systemd-tests-246.13-1.fc33.x86_64.rpm
2021/03/28 10:31:15 -05:00     210/212 : qt-x11-4.8.7-60.fc33.i686.rpm
2021/03/28 10:31:15 -05:00     211/212 : qt-x11-4.8.7-60.fc33.x86_64.rpm
2021/03/28 10:31:17 -05:00     212/212 : qt-doc-4.8.7-60.fc33.noarch.rpm
2021/03/28 10:31:18 -05:00 Importing packages started.
2021/03/28 10:31:18 -05:00 
2021/03/28 10:31:18 -05:00   Importing packages to DB:
2021/03/28 10:31:41 -05:00 value too long for type character varying(4000)

2021/03/28 10:31:41 -05:00   Package batch #5 of 19 completed...
2021/03/28 10:31:46 -05:00 value too long for type character varying(4000)

2021/03/28 10:31:46 -05:00   Package batch #3 of 19 completed...
2021/03/28 10:31:50 -05:00   Package batch #8 of 19 completed...
2021/03/28 10:31:55 -05:00   Package batch #10 of 19 completed...
2021/03/28 10:31:58 -05:00   Package batch #7 of 19 completed...
2021/03/28 10:31:59 -05:00   Package batch #9 of 19 completed...
2021/03/28 10:32:00 -05:00   Package batch #6 of 19 completed...
2021/03/28 10:32:00 -05:00   Package batch #12 of 19 completed...
2021/03/28 10:32:00 -05:00   Package batch #11 of 19 completed...
2021/03/28 10:32:08 -05:00   Package batch #19 of 19 completed...
2021/03/28 10:32:09 -05:00   Package batch #15 of 19 completed...
2021/03/28 10:32:12 -05:00   Package batch #1 of 19 completed...
2021/03/28 10:32:14 -05:00   Package batch #17 of 19 completed...
2021/03/28 10:32:15 -05:00   Package batch #18 of 19 completed...
2021/03/28 10:32:16 -05:00   Package batch #13 of 19 completed...
2021/03/28 10:32:17 -05:00   Package batch #4 of 19 completed...
2021/03/28 10:32:17 -05:00   Package batch #14 of 19 completed...
2021/03/28 10:32:17 -05:00   Package batch #16 of 19 completed...
2021/03/28 10:32:20 -05:00   Package batch #2 of 19 completed...
2021/03/28 10:32:20 -05:00 Importing packages finished.
2021/03/28 10:32:20 -05:00 
2021/03/28 10:32:20 -05:00   Linking packages to the channel.
2021/03/28 10:32:21 -05:00 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
2021/03/28 10:32:21 -05:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1127, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 777, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2505, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'aspnetcore-runtime-3.1', 'epoch': None, 'version': '3.1.13', 'release': '1.fc33', 'arch': 'x86_64', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {372: 'fedora33-x86_64-updates'}, 'checksum_list': None, 'checksum': 'bc09ff5db46cb6b1adc1cbb78f646d4e11c5526ff8c3d81bcf719823fc01ba00', 'checksum_type': 'sha256', 'checksums': {'sha256': 'bc09ff5db46cb6b1adc1cbb78f646d4e11c5526ff8c3d81bcf719823fc01ba00'}, 'name_id': 10202, 'evr_id': 369566, 'package_arch_id': 120, 'nevra_id': 852779, 'checksum_id': 33501786}] in table rhnPackage
```

**Comment by Shirocco88** [comment]
@EthanB11 : Uyuni-2021.05 was released;
could you please check if this issue is with uyuni-2021.05 fixed;
can we close this issue ?

**Comment by EthanB11** [comment]
Issue is not yet fixed.

Syncing Channel 'fedora33-x86_64' failed:

Exception reported from lm3
Time: Tue May 25 13:58:14 2021
Exception type <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>

Exception Handler Information
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1139, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2506, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'kernel-core', 'epoch': None, 'version': '5.8.15', 'release': '301.fc33', 'arch': 'x86_64', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {371: 'fedora33-x86_64'}, 'checksum_list': None, 'checksum': 'd8f263272b87175ece88f200f6b843c89c4294ee2abf630ff38485abac90fb47', 'checksum_type': 'sha256', 'checksums': {'sha256': 'd8f263272b87175ece88f200f6b843c89c4294ee2abf630ff38485abac90fb47'}, 'name_id': 99997, 'evr_id': 356021, 'package_arch_id': 120, 'nevra_id': 852402, 'checksum_id': 33486992}] in table rhnPackage

Syncing Channel 'fedora33-x86_64-updates' failed:

Exception reported from lm3
Time: Tue May 25 13:55:01 2021
Exception type <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>

Exception Handler Information
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1139, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2506, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'kernel-core', 'epoch': None, 'version': '5.12.6', 'release': '200.fc33', 'arch': 'x86_64', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {372: 'fedora33-x86_64-updates'}, 'checksum_list': None, 'checksum': 'a04414a5d6d63f83f534a905624fe2d0640500c7af852d675daa49f73e1083df', 'checksum_type': 'sha256', 'checksums': {'sha256': 'a04414a5d6d63f83f534a905624fe2d0640500c7af852d675daa49f73e1083df'}, 'name_id': 99997, 'evr_id': 374132, 'package_arch_id': 120, 'nevra_id': 876345, 'checksum_id': 35107149}] in table rhnPackage

**Comment by mcalmer** [comment]
Is it still an issue? I think there are some broken data in the DB which prevent correctly inserting.
Can you try with the latest Uyuni again or close it if this is solved.

**Comment by EthanB11** [comment]
I am no longer have a machine with Ubuntu so I can't test. Close if needed.
________________________________
