### ISSUE TITLE
Unable to create Project Lifecycle environment using API

### ISSUE THREAD

**Issue by zigford** [uyuni-project/uyuni#3525]
# Additional Information

Uyuni-Server-release:
2021.01-107.1.uyuni

## Details about issue
Unable to create Project Lifecycle environments using the api via spacecmd.

Running the following command:
`spacecmd -- api -A "sles-15.2,,update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod" contentmanagement.createEnvironment`

No apparent errors are exhibited from spacecmd, however the environment is not created.
Note that this is the first environment created on the project, so there is no predecessorLabel. However I have also manually created the first environment, and attempted to use the api to create the second environment.

I have also tried using json formatting:
```
echo $json|jq
{
  "projectLabel": "sles-15.2_nagios",
  "label": "update_group_1",
  "name": "Update Group 1A",
  "description": "1st lot of servers to get patched. Non-Prod",
  "predecessorLabel": ""
}
spacecmd -- api -A "$json" contentmanagement.createEnvironment
```

# Logs
```
[2021-04-08 13:32:47,270] INFO  - REQUESTED FROM: 172.19.25.25 CALL: api.getVersion() CALLER: (admin) TIME: 0.0 seconds
[2021-04-08 13:32:47,326] INFO  - REQUESTED FROM: 172.19.25.25 CALL: user.listAssignableRoles(admin) CALLER: (admin) TIME: 0.036 seconds
[2021-04-08 13:32:47,358] ERROR - REQUESTED FROM: 172.19.25.25 CALL: contentmanagement.createEnvironment(admin, sles-15.2_nagios, update_group_1, Update Group 1, 1st lot of servers to get patched. Non-Prod) CALLER: (admin) TIME: 0.007 seconds
redstone.xmlrpc.XmlRpcFault: Could not find method: createEnvironment in class: com.redhat.rhn.frontend.xmlrpc.contentmgmt.ContentManagementHandler with params: [com.redhat.rhn.domain.user.legacy.UserImpl, java.lang.String, java.lang.String, java.lang.String, java.lang.String]
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.findMethods(BaseHandler.java:246)
        at com.redhat.rhn.frontend.xmlrpc.BaseHandler.invoke(BaseHandler.java:117)
        at redstone.xmlrpc.XmlRpcDispatcher.dispatch(XmlRpcDispatcher.java:123)
        at com.redhat.rhn.frontend.xmlrpc.RhnXmlRpcServer.execute(RhnXmlRpcServer.java:54)
        at com.redhat.rhn.frontend.xmlrpc.XmlRpcServlet.doPost(XmlRpcServlet.java:165)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
        at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:100)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by juliogonzalez** [comment]
According to https://www.uyuni-project.org/uyuni-docs-api/uyuni/api/contentmanagement.html#apidoc-contentmanagement-createEnvironment-1814488456
```
Method: createEnvironment
Description:
Create a Content Environment and appends it behind given Content Environment
Parameters:
string sessionKey
string projectLabel - Content Project label
string predecessorLabel - Predecessor Environment label
string label - new Content Environment label
string name - new Content Environment name
string description - new Content Environment description
```
6 string parameters.

You are calling:
```
spacecmd -- api -A "sles-15.2,,update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod" contentmanagement.createEnvironment
```
So 5 string parameters.

The log says:
```
redstone.xmlrpc.XmlRpcFault: Could not find method: createEnvironment in class: com.redhat.rhn.frontend.xmlrpc.contentmgmt.ContentManagementHandler with params: [com.redhat.rhn.domain.user.legacy.UserImpl, java.lang.String, java.lang.String, java.lang.String, java.lang.String]

5 parameters, one being `com.redhat.rhn.domain.user.legacy.UserImpl` (I assume `sessionKey`) and then 4 parameters. So 1 is missing so I guess that's why you see `Could not find method: createEnvironment in class: com.redhat.rhn.frontend.xmlrpc.contentmgmt.ContentManagementHandler with params: `

I can reproduce it.

However if I try:

```
spacecmd -- api -A "sles-15.2,\"\",update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod" contentmanagement.createEnvironment
```
The the method is found and I see:
```
2021-04-08 22:25:40,171 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.frontend.xmlrpc.BaseHandler - Caused by: 
com.redhat.rhn.frontend.xmlrpc.EntityNotExistsFaultException: Entity does not exist: sles-15.2
```
At the log.

You can also avoid escaping if you instead do:
```
spacecmd -dd -- api -A 'sles-15.2,"",update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod' contentmanagement.createEnvironment
```

That said, `spacecmd` should be more friendly. 

If I run it with `-dd` I see:
```
header: Date: Thu, 08 Apr 2021 20:28:24 GMT
header: Server: Apache
header: X-Frame-Options: SAMEORIGIN
header: Content-Type: text/xml;charset=UTF-8
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Cache-Control: no-cache,no-store,must-revalidate,private
header: Pragma: no-cache
header: Expires: 0
header: Set-Cookie: JSESSIONID=709936117CD64FBF9E1E6763272FA85D; Path=/; Secure; HttpOnly; HttpOnly;HttpOnly;Secure
header: Content-Security-Policy: default-src 'self' https: wss: ; script-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: ;style-src 'self' https: 'unsafe-inline' 
header: X-XSS-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: X-Permitted-Cross-Domain-Policies: master-only
header: Content-Length: 298
body: b'<?xml version="1.0" encoding="UTF-8"?><methodResponse><fault><value><struct><member><name>faultCode</name><value><int>-1</int></value></member><member><name>faultString</name><value><string>redstone.xmlrpc.XmlRpcFault: Could not find method: createEnvironment in class: com.redhat.rhn.frontend.xmlrpc.contentmgmt.ContentManagementHandler with params: [com.redhat.rhn.domain.user.legacy.UserImpl, java.lang.String, java.lang.String, java.lang.String, java.lang.String]</string></value></member></struct></value></fault></methodResponse>'
DEBUG: api -A 'sles-15.2,,update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod' contentmanagement.createEnvironment: None
DEBUG: Undefined return code from "api -A 'sles-15.2,,update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod' contentmanagement.createEnvironment"
```

So now I wonder: I it normal that the API returns HTTP 200 OK if the call failed with `Could not find method: createEnvironment in class`, instead of HTTP 500 (Not Implemented)? @cbbayburt?

I guess that spacecmd does not show an error precisely because the server reuired HTTP 200 OK. And of course if you use ```\"\"``` HTTP 200 is returned as well even if the API call still failed.

Or maybe spacecmd just needs to check XML with the reply, and if there is `methodResponse > fault` print the error (@meaksh?)

**Comment by zigford** [comment]
Thanks @juliogonzalez 
With specifying the predecessor environment label as "", I am still unable to create the first environment.
However, it does work fine for the second environment.

Attempting to create the first environment on a project:
```
spacecmd -- api -A 'sles-15.2,"",update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod' contentmanagement.createEnvironment

[2021-04-09 14:34:16,477] ERROR - REQUESTED FROM: 172.19.25.25 CALL: contentmanagement.createEnvironment(admin, sles-15.2, "", update_group_1, Update Group 1, 1st lot of servers to get patched. Non-Prod) CALLER: (admin) TIME: 0.032 seconds
redstone.xmlrpc.XmlRpcFault: Entity of class: class com.redhat.rhn.domain.contentmgmt.ContentEnvironment does not exist: update_group_1
```

After manually creating update_group_1 via the web, creating the second environment works, but not if something has quotes.

```
spacecmd -- api -A 'sles-15.2,update_group_1,update_group_2,Update Group 2,2nd lot of servers to get patched. Non-Prod' contentmanagement.createEnvironment
[
  {
    "id": 11,
    "label": "update_group_1",
    "name": "Update Group 1",
    "description": "1st lot of servers to get patched. Non-Prod",
    "version": 0,
    "status": "unknown",
    "contentProjectLabel": "sles-15.2"
  }
]
```

This lead me to test and find that I can create the 1st environment if I specify it's predecessor label as a whitespace:
```
 spacecmd -- api -A 'sles-15.2, ,update_group_1,Update Group 1,1st lot of servers to get patched. Non-Prod' contentmanagement.createEnvironment
INFO: Connected to https://lsd-uyuni01.usc.internal/rpc/api as admin
[
  {
    "id": 12,
    "label": "update_group_1",
    "name": "Update Group 1",
    "description": "1st lot of servers to get patched. Non-Prod",
    "version": 0,
    "status": "unknown",
    "contentProjectLabel": "sles-15.2"
  }
]
```

**Comment by brejoc** [comment]
> @rjmateus This topic is on you guys, right?

Sorry, wrong squad. :point_right: @cbbayburt

**Comment by ncounter** [comment]
@zigford Hi, I addressed the bug [here](https://github.com/uyuni-project/uyuni/pull/3778). Thank you very much for reporting it. Feel free to take a look and give feedback. :beers:

**Comment by goldyfruit** [comment]
I'm still facing this issue with SUMA 4.3.12 and the REST API.

This fails:

```json
{
  "projectLabel": "2024-h1-sles15",
  "name": "dev",
  "envLabel": "dev",
  "description": "First lot of servers to get patched. Non-Prod",
  "predecessorLabel": ""
}
```

This works:
```json
{
  "projectLabel": "2024-h1-sles15",
  "name": "dev",
  "envLabel": "dev",
  "description": "First lot of servers to get patched. Non-Prod",
  "predecessorLabel": " "
}
```

**Comment by cbbayburt** [comment]
The following works for me on both SUMA 4.3.13 and the latest Uyuni.

```json
{
    "projectLabel": "myproject",
    "predecessorLabel": "",
    "envLabel": "dev",
    "name": "dev",
    "description": "Test issue #3525"
}
```

What client are you using? Is there any message in the body of the 400 response?

**Comment by goldyfruit** [comment]
> The following works for me on both SUMA 4.3.13 and the latest Uyuni.
> 
> ```json
> {
>     "projectLabel": "myproject",
>     "predecessorLabel": "",
>     "envLabel": "dev",
>     "name": "dev",
>     "description": "Test issue #3525"
> }
> ```
> 
> What client are you using? Is there any message in the body of the 400 response?

I'm confused, I'm not able to reproduce it anymore... I'm using a Python script, very basic.

Thanks for confirming that its working for you :+1:
