### ISSUE TITLE
ERROR: package 'venv-salt-minion' not found

### ISSUE THREAD

**Issue by jawahk** [uyuni-project/uyuni#7591]
### Problem description

we are trying to sync suse enterprise 12 SP5 repo and we got below error message

Error generating bootstrap repo for: SLE-12-SP5-x86_64
ERROR: package 'venv-salt-minion' not found

Please help to sort this up

### Steps to reproduce

1.go to 'admin'
2.click on 'admin wizard'
3.click on 'product' tab
4.select "SUSE Linux Enterprise Server 12 SP5 x86_64" and initiate sync 
5. after sometime you will see this error 
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2023.04-220400.204.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2023.04-220400.204.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by sbluhm** [comment]
Did you try adding the Uyuni Client Tools repo first? I believe that repo contains it.

**Comment by bigmike-19** [comment]
I find the same, if the client tools repo isn't added, you get the error about the venv-salt-minon not being found.

**Comment by avshiliaev** [comment]
I'm closing the issue as it seems like the problem is solved. Feel free to reopen if needed

**Comment by john-ye-avetta** [comment]
> I find the same, if the client tools repo isn't added, you get the error about the venv-salt-minon not being found.

how to add client tools repo, this is what i have i still get the issue

<img width="702" alt="image" src="https://github.com/uyuni-project/uyuni/assets/144408830/9540fa47-2b37-46d0-bf28-edbaf175bc69">

**Comment by rjmateus** [comment]
You can look at here [1] on how to do using the command line. You would need to add at least the Base channel and client channel to have the venv-salt-minion package.

[1] https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-debian.html

**Comment by ipanmeri** [comment]
> Uyuni Client Tools repo

Hi, I don't find info on how to add this Uyuni Client Tools repo to my Uyuni server installation.
Can anyone kindly help me?
Thanks

**Comment by rjmateus** [comment]
@ipanmeri  you need to use the command line tool `spacewalk-common-channels` to add the channels, and you can see the channel names on the link I shared before. The client tools channel is the one named "client channel" in here: https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-debian.html#_add_software_channels
