### ISSUE TITLE
Create/sync repo oraclelinux8-appstream Failed to parse buildorder in component

### ISSUE THREAD

**Issue by pititof** [uyuni-project/uyuni#9123]
### Problem description

Hello, i update my uyuni system to 2024.07 in open suse 15.6. all is up to date
ALl my repo working and sync fine (oraclelinux 7/ ubuntu 22.04/debian 12, and oraclelinux8)
but the child oraclelinux-8 appstream have an issue....
i unsubscribe my systeme, delete this channel , retry to resync it always the same issue 

2024/07/30 07:42:28 +02:00 Sync of channel started.
2024/07/30 07:42:43 +02:00
2024/07/30 07:42:43 +02:00   Importing modules file f1e8f4f94ea9c5b55639f9205d4eac1790cdb1319da89b664ccc9206d148efc6-modules.yaml.gz.
2024/07/30 07:42:43 +02:00 *** NOTE: Importing modules file for the channel 'oraclelinux8-appstream-x86_64'. Previous modules will be discarded.
2024/07/30 07:42:44 +02:00 An error occurred while reading module metadata: An error occurred while indexing a module entry:
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 158 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 158 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 170 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 175 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 157 col 9]

i try and check every thing, all repo in oraclinux8 sync evry day, but appstream... impossible to sync, or to recreate it, always the same issue appear  :(....

### Steps to reproduce

1./usr/bin/spacewalk-repo-sync --channel oraclelinux8-appstream-x86_64 --type yum --non-interactive
or
spacewalk-common-channels -a x86_64 oraclelinux8-appstream
if i delete it and recreate it
2. check the /var/log/rhn/reposync/oraclelinux8-appstream-x86_64.log
issue appear
3.
...

### Uyuni version

```bash
2024.07
```

### Uyuni proxy version (if used)

```bash
no proxy
```

### Useful logs

```bash
2024/07/30 07:42:28 +02:00 Sync of channel started.
2024/07/30 07:42:43 +02:00
2024/07/30 07:42:43 +02:00   Importing modules file f1e8f4f94ea9c5b55639f9205d4eac1790cdb1319da89b664ccc9206d148efc6-modules.yaml.gz.
2024/07/30 07:42:43 +02:00 *** NOTE: Importing modules file for the channel 'oraclelinux8-appstream-x86_64'. Previous modules will be discarded.
2024/07/30 07:42:44 +02:00 An error occurred while reading module metadata: An error occurred while indexing a module entry:
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 158 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 158 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 170 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 175 col 9]
2024/07/30 07:42:44 +02:00     Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 157 col 9]
```

**Comment by mcalmer** [comment]
AFAIK this will be fixed with the next update. 
CC @cbbayburt

**Comment by bamorrow** [comment]
any know workaround for now?

**Comment by cbbayburt** [comment]
> AFAIK this will be fixed with the next update. CC @cbbayburt

Not really, we've seen this problem in Liberty Linux repos before, but it was fixed in the repo itself. Other than that, we didn't do anything on our side.

But obviously, this is a more general problem. I'll see how we can patch against this.

**Comment by cbbayburt** [comment]
I had a deeper look, and it seems that the problem is with the `libmodulemd` python bindings (`python3-libmodulemd`)
As I understand, some bug in their build service prints those values as 64-bit unsigned instead of 64-bit signed "-1"

And when `python3-libmodulemd` tries to parse it into 64-bit signed, we see the error.

Unfortunately, there's no direct fix for us, since the parsing happens in `python3-libmodulemd` via `PyGObject`.

The only solutions I can think of are:
- Open an upstream bug and track it there
- In reposync, parse the yaml ourselves in a loop before, fixing the offending values and then passing it to `libmodulemd`

**Comment by cbbayburt** [comment]
But ultimately, the bug originates from Oracle Linux's build service. Those large values should be "-1" instead. Until we develop a workaround, another repo update from Oracle can already fix the issue.

**Comment by bamorrow** [comment]
FYI... I had found that bug referenced in RHEL8 in the past.   Their fix was to update the get an updated libmoduled that "relaxed" the scanning of the module meteadata.
https://bugzilla.redhat.com/show_bug.cgi?id=1984402
https://github.com/fedora-modularity/libmodulemd/commit/37a688cc12d7fbab67fda95c47a4605405d7a154

FYI.. In my case what I do it actually dnf reposync the ULN content to local mirror and then feed UYUNI from the local mirror. The dnf reposync to create the local mirror goes just fine with no issue, so I assume they already have the fixed libraries  in it.

**Comment by bamorrow** [comment]
Just out of curiosity, I did download a new libmodulemd and built it, then moved into place and tried the sync again, but same errors, so it is a bit more than just that. I just thought it was worth a try.

**Comment by cbbayburt** [comment]
@bamorrow yes, IIUC, our problem appeared just after that patch you linked.

From Bugzilla:

> 2.13.0 fixed a bug in parsing buildorder value. This version now complains on loading RHEL-8 repository

2.13 is what we're using. Moreover, I think the problem is not in the C part but the python bindings we're using. Dnf itself doesn't complain about it.

Also, I just remembered that Oracle accumulates all the released modules in the metadata so even another repo update won't fix the problem ever.

So that makes this issue more serious for us.

Hopefully we can fix it on our side instead of hoping another upstream fix.

**Comment by bamorrow** [comment]
I found it funny, so had to post what I found on the actually commit for that library....

+#ifdef HAVE_OVERFLOWED_BUILDORDER
+      /* A temporary hack. Remove when RHEL 8 goes end of life. */
+      if (g_str_equal ((const gchar *)event.data.scalar.value,
+                       "18446744073709551615"))
+        {
+          g_debug ("Coercing an invalid signed 64-bit integer to -1: %s",
+                   (const gchar *)event.data.scalar.value);
+          return -1;
+        }
+#endif

**Comment by bamorrow** [comment]
FYI.. in the mean time for a workaround I have setup a reposync with the option --setopt=repo_id.module_hotfixes=1
I then do a createrepo on the directory, just in case
I deleted my current channel and recreated it with a repository pointed to the new download location.

this does at least let me the create the bootstrap now. 
Hope other may use this if in the same situation.

**Comment by cbbayburt** [comment]
I can see that it's been fixed in `2.14.0` upstream: https://github.com/fedora-modularity/libmodulemd/releases/tag/2.14.0

**Comment by cbbayburt** [comment]
If you need an urgent solution, you can try building `2.14.0` yourself

**Comment by agraul** [comment]
One detail to note is that `libmodulemd-2.14.0` has a new build option to enable the behavior we need. The changelog sounds like it's not the default but opt-in. Just something to keep in mind when building it.

> Interpret an invalid buildorder 18446744073709551615 as -1 if the library
is built with a new build boolean accept_overflowed_buildorder set to true.

**Comment by bamorrow** [comment]
I actually downloaded the libmodulemd-2.15.0  and built it, with that option set.  Copied the library to /usr/lib64 and changed the symbolic links there. That did fix the issue.

**Comment by bamorrow** [comment]
In case some need this, I did the following:
zypper install git meson 
git clone https://github.com/fedora-modularity/libmodulemd.git
cd libmodulemd
edit the file meson_options.txt
change the line to read as follows:
option('accept_overflowed_buildorder', type : 'boolean', value: 'true',
       description : 'Accept overflowed 18446744073709551615 buildorder as -1. This breaks a specification, but some RHEL 8 module builds look like that.')
[you will need to install a lot of dependencies]
meson setup buildir  (until it comes up clean that dependencies are resolved)
cd buildir
ninja
ninja install
cp /usr/local/lib64/libmodulemd.so.2.15.0 /usr/lib64/
change the symlink for libmodulemd.so.2 to point to the new file
(just in case I renamed the libmodulemd.so.2.13.0 to libmodulemd.so.2.13.0.old and cp /usr/local/lib64/libmodulemd.so.2.15.0 /usr/lib64/libmodulemd.so.2.13.0)

**Comment by pititof** [comment]
@bamorrow : i follow your instruction..but at the end i have this issue:

The Meson build system
Version: 1.3.1
Source dir: /root/libmodulemd
Build dir: /root/libmodulemd/buildir
Build type: native build
Project name: modulemd
Project version: 2.15.0
C compiler for the host machine: cc (gcc 7.5.0 "cc (SUSE Linux) 7.5.0")
C linker for the host machine: cc ld.bfd 2.41.0.20230908-150100
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wpointer-arith: YES
Compiler for C supports arguments -Werror=missing-declarations: YES
Compiler for C supports arguments -Wmissing-prototypes: YES
Compiler for C supports arguments -Wstrict-prototypes: YES
Compiler for C supports arguments -Wuninitialized: YES
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES
Compiler for C supports arguments -Werror=implicit: YES
Compiler for C supports arguments -Werror=init-self: YES
Compiler for C supports arguments -Werror=main: YES
Compiler for C supports arguments -Werror=missing-braces: YES
Compiler for C supports arguments -Werror=return-type: YES
Compiler for C supports arguments -Werror=array-bounds: YES
Compiler for C supports arguments -Werror=write-strings: YES
Compiler for C supports arguments -D_GNU_SOURCE: YES
Compiler for C supports arguments -DG_LOG_USE_STRUCTURED: YES
Compiler for C supports arguments -DG_LOG_DOMAIN="libmodulemd": YES
Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
Run-time dependency gobject-2.0 found: YES 2.78.6
Run-time dependency yaml-0.1 found: YES 0.1.7
Run-time dependency rpm found: YES 4.14.3
Run-time dependency glib-2.0 found: YES 2.78.6
Program bash found: YES (/usr/bin/bash)
Program sed found: YES (/usr/bin/sed)
Program test found: YES (/usr/bin/test)
Run-time dependency gtk-doc found: YES 1.33.1

meson.build:94:6: ERROR: Problem encountered: Missing GTK documentation for glib: /usr/share/gtk-doc/html/glib/index.html

A full log can be found at /root/libmodulemd/buildir/meson-logs/meson-log.txt


:( .... i don't know what is missing....

**Comment by pititof** [comment]
I find  ^^ it's good :) the glib2-doc package ^^ was installed

**Comment by pititof** [comment]
I try your git, it's works fine !!!

for all user, before launch the meson setup build, the dependencies you need to install is: 

 zypper install git meson
 zypper install cmake
 zypper install gobject
zypper install gobject-introspection
zypper install gobject-introspection-devel
zypper install libyaml-devel
zypper install rpm-deve
zypper install gtk-doc
zypper install glib2-doc

**Comment by jay2theb** [comment]
Thank you @pititof and @bamorrow your workaround worked for me on a rhel8 repo on 2024.07 also.

**Comment by bamorrow** [comment]
I did manage to build a set rpm to replace the system ones with libmodule 2.15.0

**Comment by stdevel** [comment]
Second. I also have this on a brand-new Uyuni 2024.08 running in a container. Will try the workaround later.

**Comment by fritz0011** [comment]
@bamorrow  for the lazy guys :) can you upload here or somewhere else the newly compiled libmodule ? 
I suppose you did it  for SLES 15 ?

**Comment by stdevel** [comment]
I built the attached library yesterday on a openSUSE Leap 15.5 machine and successful used it in the Uyuni 2024.08 container image. Should also work with SUMA 5.x aswell, I assume. Simply remove the symlink and copy the library before creating a new one:

```shell
# cp libmodulemd.so.2.15.0 /usr/lib64/
# rm /usr/lib64/libmodulemd.so.2
# ln -s /usr/lib64/libmodulemd.so.2.15.0 /usr/lib64/libmodulemd.so.2
# ls -la /usr/lib64/*modulemd*
lrwxrwxrwx. 1 root root      21 Aug 29 13:32 libmodulemd.so.2 -> libmodulemd.so.2.15.0
-rwxr-xr-x. 1 root root  482088 May  8  2022 libmodulemd.so.2.13.0
-rw-r--r--. 1 root root 2273656 Aug 29 13:31 libmodulemd.so.2.15.0
```

**NOTE**: Keep in mind that this change is **not** persistent, once the container is restarted, the old library will be used again.

[libmodulemd.so.2.15.zip](https://github.com/user-attachments/files/16814633/libmodulemd.so.2.15.zip)

**Comment by fritz0011** [comment]
yes, deployed to a standard opensuse install, so, finally oracle and rhel8 appstream are able to sync :)

**Comment by RenownTwiz** [comment]
Do we know if a permanent fix for this will be included in 2024.09?

I just ran through the above workaround steps on the container install via "mgrctl term" and it works in v2024.08.  The only thing to note is that you have to modify /etc/zypp/zypp.conf with "rpm.install.excludedocs = no" because of a build dependency for a file in glib2-doc.

Error you get without changing rpm.install.excludedocs doing that is:
meson.build:94:6: ERROR: Problem encountered: Missing GTK documentation for glib: /usr/share/gtk-doc/html/glib/index.html

**Comment by cbbayburt** [comment]
> Do we know if a permanent fix for this will be included in 2024.09?

Since the bug is in an external library (libmodulemd), it'll be fixed when an update is available in the host OS (Leap, Leap Micro). We'll push for an update there hopefully soon.

**Comment by RenownTwiz** [comment]
I might be wrong, but it sounds like the thought here is that accept_overflowed_buildorder would be set to "True" in the build of libmodulemd.so.2.15.0 or later in a future openSUSE MicroOS release?  It looks like that value is defaulted to "False" when you pull the library from the git repo.  What's to say they don't include a new version of libmodulemd in next release of MicroOS but leave accept_overflowed_buildorder set to "False" which wouldn't fix the issue right?  This breaks most RHEL/OEL/etc v8 distros from what I can see so its pretty major.  Workaround seems okay for VM builds, but a bit harder to support on the new Podman installed version, would it make sense to temporarily bake the fix into the container image itself, then when it's fixed upstream in MicroOS that could be removed?

**Comment by stdevel** [comment]
Could be possible as openSUSE MicroOS is based openSUSE Tumbleweed (rolling-release) while openSUSE Leap Micro is based on openSUSE Leap. Uyuni requires the latter and thus has the outdated version.

**Comment by oldvladko** [comment]
Fix for/etc/zypp/zypp.conf didn't work for me. Had to install  old glib2-doc-2.70.5-150400.3.11.1.x86_64 which provides the required /usr/share/gtk-doc/html/glib/index.html . Once it's done the repos  started to sync.

**Comment by RenownTwiz** [comment]
Upgraded my test containerized Uyuni install from 2024.08 to 2024.10 today.  Was testing through this and I'm not 100% sure if it is fixed in 2024.10?  I still see libmodulemd.so.2.13.0 being used in the container image.

_uyuni-server:/usr/lib64 # ls -la libmodulemd*
lrwxrwxrwx. 1 root root     21 Aug 14 14:44 libmodulemd.so.2 -> libmodulemd.so.2.13.0
-rwxr-xr-x. 1 root root 482064 Aug 14 14:45 libmodulemd.so.2.13.0_

But, when I test a sync of the OELv8 Appstream repo the behavior has changed.  I still see the "The integer value is larger than" error messages but the sync appears to skip on past them and continue and complete.

Can someone confirm if this was fixed with a workaround of some kind and the error messages are okay to ignore?

Thanks.

FYI log looks like below now:

uyuni-server:/var/log/rhn/reposync # /usr/bin/spacewalk-repo-sync --channel oraclelinux8-appstream-x86_64 --type yum --non-interactive
12:53:45 ======================================
12:53:45 | Channel: oraclelinux8-appstream-x86_64
12:53:45 ======================================
12:53:45 Sync of channel started.
Retrieving repository 'oraclelinux8-appstream-x86_64' metadata .............................................................................................................[done]
Building repository 'oraclelinux8-appstream-x86_64' cache ..................................................................................................................[done]
All repositories have been refreshed.
12:53:59
12:53:59   Importing modules file 855381608c1ad7f0cdbeb3181c0c0c19e53ddf4dbb448975719a5d87709134b7-modules.yaml.gz.
12:53:59 *** NOTE: Importing modules file for the channel 'oraclelinux8-appstream-x86_64'. Previous modules will be discarded.
12:53:59 Following error(s) occurred while indexing module entries:
12:53:59   modulemd-yaml-error-quark: Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 158 col 9] (3)
12:53:59   modulemd-yaml-error-quark: Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 158 col 9] (3)
12:53:59   modulemd-yaml-error-quark: Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 170 col 9] (3)
12:53:59   modulemd-yaml-error-quark: Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 175 col 9] (3)
12:53:59   modulemd-yaml-error-quark: Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 157 col 9] (3)
12:53:59
12:53:59   Importing comps file d4eeaef852527b87e42ab1c2667fdb684d6feafc0c59db686462ed1469c7b832-comps.xml.
12:53:59   Renaming non-standard filename d4eeaef852527b87e42ab1c2667fdb684d6feafc0c59db686462ed1469c7b832-comps.xml to comps.xml.
12:53:59 *** NOTE: Importing comps file for the channel 'oraclelinux8-appstream-x86_64'. Previous comps will be discarded.
12:54:01 Repo URL: https://yum.oracle.com/repo/OracleLinux/OL8/appstream/x86_64/
12:54:01     Packages in repo:             51800
12:56:02     No new packages to sync.
12:56:02 Filtering packages that failed to download
12:56:02
12:56:02   Importing packages to DB:
12:56:02   Importing module metadata:
12:56:02     Modules in repo: 55
12:56:02 0 new package(s) imported for module 389-ds:1.4:20190512202313:1fc8b219:x86_64.
..
..
12:56:24 0 new package(s) imported for module virt:ol:8090020231206155326:a75119d5:x86_64.
12:56:24 0 new package(s) imported for module virt:ol:8100020240523015105:63b34585:x86_64.
12:56:40
12:56:40   Patches in repo: 3992.
12:56:46 Add Patch ELBA-2020-5668
12:56:46 Add Patch ELBA-2020-5679
12:56:48 Add Patch ELBA-2020-5809
12:56:48 Add Patch ELBA-2020-5896
12:56:50 Add Patch ELBA-2020-5986
12:56:51 Add Patch ELBA-2021-9174
12:56:59     No new patch to sync.
12:57:01 Sync completed.
12:57:01 Total time: 0:03:16

**Comment by RenownTwiz** [comment]
Sorry I think I just answered my own question.  I didn't notice the comment on the close of this:  "[pititof](https://github.com/pititof) opened this issue on Jul 30 · 28 comments · Fixed by https://github.com/uyuni-project/uyuni/pull/9267"

I looked at 9267 and it answers my question, the errors are now ignored.  So we should be all good here.  Thanks.

**Comment by cbbayburt** [comment]
@RenownTwiz yes, this is the expected behavior now. We fixed the issue in Uyuni, so you don't have to update libmodulemd anymore.

We kept printing the errors for information but it doesn't affect operation anymore.

Everything looks fine in your output.

**Comment by AdamWyzgol** [comment]
I am using containerized Uyuni 2026.06 with Python 3.13.

The known buildorder errors still appear, but synchronization also raises
repeated exceptions during import_package_batch:

TypeError: startswith first arg must be str or a tuple of str, not bytes

at:
uyuni/common/rhn_rpm.py, modularity_label()
self.hdr[rpm.RPMTAG_DISTTAG].startswith(b"module(")

This appears to have functional impact. For example, Oracle's current OL8
AppStream metadata contains:

nodejs-docs-1:12.20.1-1.module+el8.3.0+9643+8c99e187.noarch

but the exact EVR is absent from rhnPackage after a clean synchronization.
Consequently ELSA-2021-0549 is skipped.

The problem is reproducible with a newly created empty channel and after
clearing /var/cache/rhn/reposync.

Is this considered part of #9123/#9267, or should I open a separate issue?
