### ISSUE TITLE
symlinked states inside /srv/salt stopped working after update to 2024.07 (saltstack 3006)

### ISSUE THREAD

**Issue by fd-SR** [uyuni-project/uyuni#9165]
### Problem description

We use a couple of custom salt formulas in Uyuni. 
To allow managing changes to these formulas directly in a state-channel inside the Uyuni GUI, we symlinked the relevant files and folders from inside the folders of that state-channel into _srv/salt_ and _/srv/formula_metadata_ so that they actually function as formulas. 
This used to work fine, but after the last update to 2024.07 the related states fail.
In the GUI the formula still appear fine, but when an actual related state is applied, it fails.
It looks like this may be related to a saltstack issue([https://github.com/saltstack/salt/issues/66133]), which is supposed to be fixed in saltstack 3006.9 (according to the ticket). 
I worked around it for now by actually syncing the files into the _/srv/salt_ folder and the states work fine again then. 
But I was wondering when or if this fix might make its way into Uyuni's saltstack?

### Steps to reproduce

1.Symlink state file or folder containing state file into _/srv/salt_
2.Try to apply that state
3.State fails as not being found in saltenv 'base'
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.07-230900.219.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.07-230900.219.1.uyuni3.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by rjmateus** [comment]
I think the fix for this issue is already included in the latest uyuni version. @agraul could you confirm?

**Comment by mcalmer** [comment]
This should be fixed

**Comment by fd-SR** [comment]
After upgrading from 2024.07 to 2024.12 I wanted to revert to the symlinked folders.
But after reverting to the symlinks the related states stopped working again. 
So I think the problem still persists.
Here our current version info:
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.12-241000.225.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.12-241000.225.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
