### ISSUE TITLE
Oracle Linux 8 - Remi Repo Sync Failure

### ISSUE THREAD

**Issue by TuxOps-lab** [uyuni-project/uyuni#9848]
### Problem description

Syncing Remi Repo fails with PREPENDED_DIR

### Steps to reproduce

1. Try to sync ol8 Repo Remi with Url: http://cdn.remirepo.net/enterprise/8/remi/x86_64/mirror
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.12-241000.225.1.uyuni5
Arch           : x86_64
Vendor         : openSUSE
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : No
Status         : not installed
Source package : Uyuni-Server-release-2024.12-241000.225.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash

```

### uyuni-tools version used to deploy/manage the server or proxy (if relevant)

```bash

```

### Useful logs

```bash
14:18:57     6756/6758 : wordpress-6.7.1-1.el8.remi.noarch.rpm
14:19:04     6757/6758 : wordpress-6.7.2-1.el8.remi.noarch.rpm
14:19:13     6758/6758 : wkhtmltopdf-opt-0.12.4-3.el8.remi.x86_64.rpm
14:19:14 Filtering packages that failed to download
14:19:14 
14:19:14   Importing packages to DB:
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
```

**Comment by dfaltum** [comment]
I think this is fixed here: https://github.com/uyuni-project/uyuni/pull/8916

**Comment by agraul** [comment]
Thank you for the bug report @Uyunifier! We have had similar issues in the past. I'm adding this to our internal tracker.

@dfaltum that's the same type of error, but #8916 does not fix this. For both errors, the problem is that we look for a configuration value in the wrong place. `rhnConfig` internally splits the "namespaces" of  our config (`/etc/rhn/rhn.conf`). When we access a config value, we first specify the namespace (called _component_ in the code) and then access the "name" of the the config value, e.g. `PREPENDED_DIR`. This error occurs when the wrong namespace is used.

**Comment by m-czernek** [comment]
Looking at this issue, I don't believe this is related to a particular repository you're trying to sync. On my test server, I managed to sync the repo without problems multiple times:

```
...
14:48:56     6765/6768 : unit-1.34.1-1.el8.remi.x86_64.rpm
14:48:57     6766/6768 : unit-1.34.2-1.el8.remi.x86_64.rpm
14:49:09     6767/6768 : wordpress-6.7.2-1.el8.remi.noarch.rpm
14:49:19     6768/6768 : wkhtmltopdf-opt-0.12.4-3.el8.remi.x86_64.rpm
14:49:19 
14:49:19   Importing packages to DB:
14:49:20   Package batch #2 of 339 completed...
14:49:21   Package batch #1 of 339 completed...
...
14:51:27   Linking packages to the channel.
14:51:28     1000 packages linked
...
14:52:00 Sync completed.
14:52:00 Total time: 0:07:07
```

While I'm looking deeper into the issue, @Uyunifier , I have a few questions:

- Would you be willing to share your `/etc/rhn/rhn.conf` file? (Note, if you do, please remove any username / password / secret / ...  - you can also send it to my `name.surname@suse.com` email, which you can either compose from the name in my profile, or find it in the git log of the `uyuni-project/uyuni` repository)
- Is the fail consistent? I.e. when you re-try syncing the repository, do you always get this error?
- Can you sync other repositories without issues?

**Comment by m-czernek** [comment]
Interesting, thank you for the report! So it seems it is not related to any particular repo, but a sporadic issue with reposync that can just happen.

Would you be willing to test the following diff? [1] If you prefer, you can turn it into a `patch` compatible diff at [2].

I haven't been able to reproduce the issue, but I've seen it a few times. This is, so far, our best guess as to why it's happening.

[1] https://github.com/uyuni-project/uyuni/pull/10013/files
[2] https://patch-diff.githubusercontent.com/raw/uyuni-project/uyuni/pull/10013.diff

**Comment by m-czernek** [comment]
Well, this is surprising... The good news is that the exception is different, so we're moving somewhere. The strange news is that we already fixed `ENABLE_NVREA` where reposync touches anything (at least to the best of my knowledge).

Could you also try [1]? (If you reverted the diff, then [2].) 
I suspect the result is going to be the same, but it's worth trying.

In the mean time, the biggest problem I'm facing is that the whole exception from `import_package_batch` gets truncated due to `multiprocessing.Pool`, so we're blind here.

In the mean time, I'll think about how we can get more information out of `import_package_batch`. The fact that I cannot reproduce the issue makes this much harder than it should be :/

[1] https://github.com/uyuni-project/uyuni/commit/d3f6455b20e2e9972c15b46249a0371ed1e0c2a4.diff
[2] https://patch-diff.githubusercontent.com/raw/uyuni-project/uyuni/pull/10013.diff

**Comment by m-czernek** [comment]
Actually, I realized we can get the full exception fairly easily. 

@Uyunifier , can you please apply this diff [1] and run the reposync again? This should give us more understanding of what precisely's going on with `ENABLE_NVREA` - I've got some ideas of what we could do there, but first I wanted to see exactly what was failing for you.

Again, if you have reverted the original diff, feel free to re-apply the whole PR again at [2].

[1] https://github.com/uyuni-project/uyuni/commit/da1d5e198c6c4323776b6bbcc96840244fa456de.diff
[2] [2] https://patch-diff.githubusercontent.com/raw/uyuni-project/uyuni/pull/10013.diff

**Comment by m-czernek** [comment]
Ha! The diff had `log(0, "traceback.format_exc()")` but it should have been `log(0, traceback.format_exc())`! 

My apologies, this was a silly typo!

Can you please try [1]?

[1] https://github.com/uyuni-project/uyuni/pull/10013/commits/89bb180e1121750ca043cd7e07457469b1f4e160

**Comment by m-czernek** [comment]
You seem to have reverted the PR? In that case, you can apply the full diff [0] and not just the incremental commit.

[0] https://patch-diff.githubusercontent.com/raw/uyuni-project/uyuni/pull/10013.diff

**Comment by ycedres** [comment]
The traceback shown in the previous comment seems not to be related to the original issue about `PREPENDED_DIR` configuration property being wrongly accessed. Does this happen with the patch in https://patch-diff.githubusercontent.com/raw/uyuni-project/uyuni/pull/10013.diff reverted?

**Comment by denyskon** [comment]
> Interesting, thank you for the report! So it seems it is not related to any particular repo IIUIC, but a sporadic issue with reposync that can just happen? Or did you mean that this happened with the same repository?
> 
> Would you be willing to test the following diff? [1] If you prefer, you can turn it into a `patch` compatible diff at [2].
> 
> I haven't been able to reproduce the issue, but I've seen it a few times. This is, so far, our best guess as to why it's happening.
> 
> [1] https://github.com/uyuni-project/uyuni/pull/10013/files [2] https://patch-diff.githubusercontent.com/raw/uyuni-project/uyuni/pull/10013.diff

@m-czernek After a fresh install of Uyuni 2025.07 and trying to sync Debian repos, the same issue as described here occurred for me. It is probably originally caused by our proxy which sometimes fails when downloading many large files, so some portion of the sync fails to download. If this occurs, thus if not all packages could be successfully downloaded, the whole import fails with the PREPENDED_DIR message.
However, the first patch you linked solves the issue for us, the portion of the packages which had been downloaded are being imported, with the remaining ones being picked up in the next sync.
Could you please reopen the issue?

**Comment by m-czernek** [comment]
Thank you for the comment @denyskon - we have merged the PR you're referring to in August, only that it has not yet been released.

If the PR fully fixes the issue for you, then I don't think we need to re-open this issue. You can keep the patch in your current deployment, and when you update your Uyuni deployment, it'll contain it as well, so your environment should just continue working.

**Comment by denyskon** [comment]
Great, thanks a lot!
